const blooMoon;
console.log(blooMoon);
const mountainSky;
console.log(mountainSky);
const riverLay;
console.log(riverLay);
const landOwner;
console.log(landOwner);
const bikeRace;
console.log(bikeRace);
const damAside;
console.log(damAside);
const renderStreet;
console.log(renderStreet);
const remoteWork;
console.log(remoteWork);
const lockTail;
console.log(lockTail);
const riceBrand;
console.log(riceBrand);
const comSci;
console.log(comSci);
const hitGel;
console.log(hitGel);
const univerSity;
console.log(univerSity);
const abiNaya;
console.log(abiNaya);
const briYani;
console.log(briYani);
const cricKet;
console.log(cricKet);
const lazyMoon;
console.log(lazyMoon);
const rootHerb;
console.log(rootHerb);
const earthPlanet;
console.log(earthPlanet);
const marsMass;
console.log(marsMass);


