let blooMoon;
console.log(blooMoon);
let mountainSky;
console.log(mountainSky);
let riverLay;
console.log(riverLay);
let landOwner;
console.log(landOwner);
let bikeRace;
console.log(bikeRace);
let damAside;
console.log(damAside);
let renderStreet;
console.log(renderStreet);
let remoteWork;
console.log(remoteWork);
let lockTail;
console.log(lockTail);
let riceBrand;
console.log(riceBrand);
let comSci;
console.log(comSci);
let hitGel;
console.log(hitGel);
let univerSity;
console.log(univerSity);
let abiNaya;
console.log(abiNaya);
let briYani;
console.log(briYani);
let cricKet;
console.log(cricKet);
let lazyMoon;
console.log(lazyMoon);
let rootHerb;
console.log(rootHerb);
let earthPlanet;
console.log(earthPlanet);
let marsMass;
console.log(marsMass);


