var blooMoon;
console.log(blooMoon);
var mountainSky;
console.log(mountainSky);
var riverLay;
console.log(riverLay);
var landOwner;
console.log(landOwner);
var bikeRace;
console.log(bikeRace);
var damAside;
console.log(damAside);
var renderStreet;
console.log(renderStreet);
var remoteWork;
console.log(remoteWork);
var lockTail;
console.log(lockTail);
var riceBrand;
console.log(riceBrand);
var comSci;
console.log(comSci);
var hitGel;
console.log(hitGel);
var univerSity;
console.log(univerSity);
var abiNaya;
console.log(abiNaya);
var briYani;
console.log(briYani);
var cricKet;
console.log(cricKet);
var lazyMoon;
console.log(lazyMoon);
var rootHerb;
console.log(rootHerb);
var earthPlanet;
console.log(earthPlanet);
var marsMass;
console.log(marsMass);


